{{- if .Values.branding.cssOverrides }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "weaura-grafana.fullname" . }}-css-overrides
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "weaura-grafana.labels" . | nindent 4 }}
    app.kubernetes.io/component: branding
data:
  custom.css: |
    {{ .Values.branding.cssOverrides | indent 4 }}
{{- end }}
